# Welcom to numpy

In [1]:
import numpy as np

In [2]:
myarr = np.array([2,3,4,5,6,3] , np.int64)

In [3]:
myarr

array([2, 3, 4, 5, 6, 3], dtype=int64)

In [4]:
myarr[1]

3

In [5]:
myarr.shape

(6,)

In [6]:
myarr.dtype

dtype('int64')

In [7]:
myarr[3]=23

In [8]:
myarr

array([ 2,  3,  4, 23,  6,  3], dtype=int64)

In [9]:
myarr[0]

2

In [10]:
myarr.shape

(6,)

In [11]:
myarr.shape

(6,)

In [12]:
myarr[4]

6

In [13]:
myarr[4]=35

In [14]:
myarr[4]

35

In [15]:
myarr

array([ 2,  3,  4, 23, 35,  3], dtype=int64)

# Array creation: conversion fro python structures

In [16]:
dimensarray = np.array([[2,56,34],[4,6,54],[34,3,45]])

In [17]:
dimensarray

array([[ 2, 56, 34],
       [ 4,  6, 54],
       [34,  3, 45]])

In [18]:
dimensarray.size

9

In [19]:
dimensarray.shape

(3, 3)

In [20]:
dimensarray.dtype

dtype('int32')

In [21]:
zeros = np.zeros((2,4))

In [22]:
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
zeros.dtype

dtype('float64')

In [24]:
zeros.shape

(2, 4)

In [25]:
zeros.size

8

In [26]:
ranges = np.arange(20)

In [27]:
ranges.dtype

dtype('int32')

In [28]:
ranges

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [29]:
lspace = np.linspace(1,10,15)

In [30]:
lspace

array([ 1.        ,  1.64285714,  2.28571429,  2.92857143,  3.57142857,
        4.21428571,  4.85714286,  5.5       ,  6.14285714,  6.78571429,
        7.42857143,  8.07142857,  8.71428571,  9.35714286, 10.        ])

In [31]:
emty = np.empty((4,6))

In [32]:
emty

array([[4.94065646e-324, 1.27319747e-313, 9.80058112e+252,
        1.21211036e-311, 1.35617278e+248, 5.62349085e-062],
       [1.48539705e-313, 2.54639495e-313, 6.58060804e-066,
        1.21212085e-311, 1.21211036e-311, 8.37170362e-144],
       [4.94065646e-324, 2.54639495e-313, 1.52202239e+188,
        1.21211036e-311, 8.03704157e-095, 4.24511423e+175],
       [1.48539705e-313, 2.54639495e-313, 6.00465779e-143,
        1.21212085e-311, 1.21211036e-311, 4.51223666e-037]])

In [33]:
emp_like = np.empty_like(lspace)

In [34]:
emp_like

array([ 1.        ,  1.64285714,  2.28571429,  2.92857143,  3.57142857,
        4.21428571,  4.85714286,  5.5       ,  6.14285714,  6.78571429,
        7.42857143,  8.07142857,  8.71428571,  9.35714286, 10.        ])

In [35]:
idt = np.identity(4)

In [36]:
idt

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [37]:
idt.shape

(4, 4)

In [38]:
idt.size

16

In [39]:
idt[2,3]=6

In [40]:
idt

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 6.],
       [0., 0., 0., 1.]])

In [41]:
arr = np.arange(99)

In [42]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [43]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [44]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [45]:
arr = arr.reshape(3,33)

In [46]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [47]:
arr = arr.ravel()

In [48]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [49]:
araxis = np.array([[1,23,3],
                  [3,5,9],
                 [4,2,8]])

In [50]:
araxis

array([[ 1, 23,  3],
       [ 3,  5,  9],
       [ 4,  2,  8]])

In [51]:
sumaxis.sum(axis=0)

NameError: name 'sumaxis' is not defined

In [ ]:
araxis.sum(axis=0)

In [ ]:
araxis.sum(axis=1)

In [ ]:
araxis.T

In [ ]:
for i in araxis.flat:
    print(i)

In [ ]:
ar.ndim

In [ ]:
araxis.ndim

In [ ]:
araxis.size

In [ ]:
araxis.size

In [ ]:
araxis.nbytes

In [ ]:
one = np.array([1,4,3,5,456,3,3])

In [ ]:
one.argmax()

In [ ]:
one.argsort()

In [ ]:
one.argsort(axis=0)

In [ ]:
araxis.argsort(axis=1)

In [ ]:
araxis.argsort(axis = 0)

In [ ]:
one.ravel()

In [ ]:
one

In [ ]:
araxis.ravel()

In [ ]:
one.reshape((1,7))

In [ ]:
one2=np.array([[ 7, 4,  3],
       [ 9,  8,  8],
       [ 1,  3,  97]])

In [ ]:
one + one2

In [ ]:
araxis + one2

In [ ]:
araxis * one2

In [ ]:
araxis / one2

In [ ]:
araxis - one2

In [ ]:
np.sqrt(one2)

In [ ]:
one2.sum(axis=1)

In [ ]:
one2.sum(axis=0)

In [ ]:
one2

In [ ]:
np.where(one2 > 4)

In [ ]:
np.count_nonzero(one2)

In [ ]:
np.nonazero(one2)

In [ ]:
one.tolist()

In [ ]:
arraxi.shape()

In [ ]:
araxis.shape()

In [ ]:
arr.head()

In [ ]:
arr.shape()

In [52]:
arr.shape()

TypeError: 'tuple' object is not callable