# Welcom to numpy

In [1]:
import numpy as np

In [2]:
myarr = np.array([2,3,4,5,6,3] , np.int64)

In [3]:
myarr

array([2, 3, 4, 5, 6, 3], dtype=int64)

In [4]:
myarr[1]

3

In [5]:
myarr.shape

(6,)

In [6]:
myarr.dtype

dtype('int64')

In [7]:
myarr[3]=23

In [8]:
myarr

array([ 2,  3,  4, 23,  6,  3], dtype=int64)

In [9]:
myarr[0]

2

In [10]:
myarr.shape

(6,)

In [11]:
myarr.shape

(6,)

In [12]:
myarr[4]

6

In [13]:
myarr[4]=35

In [14]:
myarr[4]

35

In [15]:
myarr

array([ 2,  3,  4, 23, 35,  3], dtype=int64)

# Array creation: conversion fro python structures

In [16]:
dimensarray = np.array([[2,56,34],[4,6,54],[34,3,45]])

In [17]:
dimensarray

array([[ 2, 56, 34],
       [ 4,  6, 54],
       [34,  3, 45]])

In [18]:
dimensarray.size

9

In [19]:
dimensarray.shape

(3, 3)

In [20]:
dimensarray.dtype

dtype('int32')

In [21]:
zeros = np.zeros((2,4))

In [22]:
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
zeros.dtype

dtype('float64')

In [24]:
zeros.shape

(2, 4)

In [25]:
zeros.size

8

In [26]:
ranges = np.arange(20)

In [27]:
ranges.dtype

dtype('int32')

In [28]:
ranges

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [29]:
lspace = np.linspace(1,10,15)

In [30]:
lspace

array([ 1.        ,  1.64285714,  2.28571429,  2.92857143,  3.57142857,
        4.21428571,  4.85714286,  5.5       ,  6.14285714,  6.78571429,
        7.42857143,  8.07142857,  8.71428571,  9.35714286, 10.        ])

In [31]:
emty = np.empty((4,6))

In [32]:
emty

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.37961438e-306, 1.89146896e-307, 7.56571288e-307],
       [3.11525958e-307, 1.24610723e-306, 1.37962320e-306,
        1.29060871e-306, 2.22518251e-306, 1.33511969e-306],
       [1.78022342e-306, 1.05700345e-307, 1.24610383e-306,
        1.69118108e-306, 8.06632139e-308, 1.20160711e-306],
       [1.69119330e-306, 1.29062229e-306, 1.29060531e-306,
        2.13620807e-306, 1.69118787e-306, 2.56765117e-312]])

In [33]:
emp_like = np.empty_like(lspace)

In [34]:
emp_like

array([ 1.        ,  1.64285714,  2.28571429,  2.92857143,  3.57142857,
        4.21428571,  4.85714286,  5.5       ,  6.14285714,  6.78571429,
        7.42857143,  8.07142857,  8.71428571,  9.35714286, 10.        ])

In [35]:
idt = np.identity(4)

In [36]:
idt

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [37]:
idt.shape

(4, 4)

In [38]:
idt.size

16

In [39]:
idt[2,3]=6

In [40]:
idt

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 6.],
       [0., 0., 0., 1.]])

In [41]:
arr = np.arange(99)

In [42]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [46]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [47]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [48]:
arr = arr.reshape(3,33)

In [49]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [50]:
arr = arr.ravel()

In [51]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [52]:
araxis = np.array([[1,23,3],
                  [3,5,9],
                 [4,2,8]])

In [53]:
araxis

array([[ 1, 23,  3],
       [ 3,  5,  9],
       [ 4,  2,  8]])

In [54]:
sumaxis.sum(axis=0)

NameError: name 'sumaxis' is not defined

In [55]:
araxis.sum(axis=0)

array([ 8, 30, 20])

In [56]:
araxis.sum(axis=1)

array([27, 17, 14])

In [58]:
araxis.T

array([[ 1,  3,  4],
       [23,  5,  2],
       [ 3,  9,  8]])