# Welcom to numpy

In [1]:
import numpy as np

In [2]:
myarr = np.array([2,3,4,5,6,3] , np.int64)

In [3]:
myarr

array([2, 3, 4, 5, 6, 3], dtype=int64)

In [4]:
myarr[1]

3

In [5]:
myarr.shape

(6,)

In [6]:
myarr.dtype

dtype('int64')

In [7]:
myarr[3]=23

In [8]:
myarr

array([ 2,  3,  4, 23,  6,  3], dtype=int64)

In [9]:
myarr[0]

2

In [10]:
myarr.shape

(6,)

In [11]:
myarr.shape

(6,)

In [13]:
myarr[4]

6

In [14]:
myarr[4]=35

In [15]:
myarr[4]

35

In [16]:
myarr

array([ 2,  3,  4, 23, 35,  3], dtype=int64)

# Array creation: conversion fro python structures

In [19]:
dimensarray = np.array([[2,56,34],[4,6,54],[34,3,45]])

In [20]:
dimensarray

array([[ 2, 56, 34],
       [ 4,  6, 54],
       [34,  3, 45]])

In [21]:
dimensarray.size

9

In [22]:
dimensarray.shape

(3, 3)

In [ ]:
dimensarray.dtype